version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: './server'
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
  client:
    build:
      dockerfile: Dockerfile
      context: './client'
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
